import { createElement } from 'lwc';
import Modal from 'c/modal';

async function flushPromises(){
    return Promise.resolve();
}

describe('c-modal', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', async() => {
        const element = createElement('c-modal', {
            is: Modal
        });
        document.body.appendChild(element);

        const icon = element.shadowRoot.querySelector('lightning-button-icon');
        icon.dispatchEvent(new CustomEvent('click'));
        const slot = element.shadowRoot.querySelectorAll('slot');
        slot[1].dispatchEvent(new CustomEvent('slotchange'));
        slot[3].dispatchEvent(new CustomEvent('slotchange'));
        await flushPromises();
        expect(icon).not.toBe(null);
    });
});