import { createElement } from 'lwc';
import RelatedListNewEditPopup from 'c/relatedListNewEditPopup';

describe('c-related-list-new-edit-popup', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-related-list-new-edit-popup', {
            is: RelatedListNewEditPopup
        });
        document.body.appendChild(element);
        element.show();
        const modal = element.shadowRoot.querySelector('c-modal');
        modal.dispatchEvent(new CustomEvent('closedialog'))
        expect(1).toBe(1);
    });
});